spring:
  profiles:
    group:
      test:
        - "core"
        - "core-test"
      default:
        - "core"
        - "core-default"
      qa:
        - "core"
        - "core-qa"
      prod:
        - "core"
        - "core-prod"
  application:
    name: transaction-api
