version: "3.7"
services:
  postgres:
    container_name: postgres-transaction
    image: postgres:14.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: transactiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    env_file:
      - docker-compose.env
    networks:
      - postgres

  server:
    container_name: pismo-challenge
    depends_on:
      - postgres
    build: .
    ports:
      - "8080:8080"
    env_file:
      - docker-compose.env
    environment:
      JAVA_OPTS: -Xms256m -Xmx512m
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
