spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/transactiondb}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      connection-test-query: select 1
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        connection:
          driver_class: org.postgresql.Driver
        show_sql: false
        format_sql: false
        use_sql_comments: false
